title: 凌风的小窝
subtitle: 大黄蜂的个人空间
description: 大黄蜂的个人空间
keywords: Java, Blog
author: 大黄蜂
language: zh-CN
timezone: null
url: https://www.xuhuanfeng.cn
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: icarus
deploy:
  type: git
  repository: https://github.com/xuhuanfeng/xuhuanfeng.github.io.git
  branch: master
